name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4.1.2

    - name: Docker login
      uses: docker/login-action@v3.1.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./docker/build
        build-args: |
          PHP_VERSION=8.3.4-fpm-bullseye
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/laravel:latest
          ${{ secrets.DOCKER_USERNAME }}/laravel:php8.3.4

